spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: ACCOUNT-SERVICE

server:
  port: 8083


error:
  application:
    code: 3001
    message: "Application Not Found"


