spring:
  application:
    name: TRANSACTION-SERVICE-ONLINE-BANKING
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    non-secure-port: ${server.port}

account:
  kyc:
    initiated: "INITIATED"
    updated: "UPDATED"
  transaction-count:
    limit: 5


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    fallback:
      registerHealthIndicator: true
      event-consumer-buffer-size: 5
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      failureRateThreshold: 50
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 6s
      automaticTransitionFromOpenToHalfOpenEnabled: true

logging:
  level:
    com:
      onlinebanking:
        transactionservice: info
  file:
    name: appLog.log
  pattern:
    file: "%d [%level] %c{1.} [%t] %m%n"